name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    my_first_job:
      steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

    my_first_job2:
      steps:
      - run: surefire:test -Dgroups="com.sdet.auto.groups.ContainersTest"

